import model.EcucModel;

public class EcucExtractor {
    
    public static void main(String[] args) throws Exception {
        
        EcucModel ecucDataModel = new EcucModel();
        ecucDataModel.initialize();

        // Print the model to verify
        System.out.println(ecucDataModel);

        // The following part shall be generated by Copilot based on the instructions in COPILOT_INSTRUCTIONS.md
        // Copilot: start writing your code here

        // Copilot: stop writing your code here
    }
}
