import model.EcucModel;

public class EcucExtractor {
    
    public static void main(String[] args) throws Exception {
        
        EcucModel ecucDataModel = new EcucModel();
        ecucDataModel.initialize();

        // Print the model to verify
        System.out.println(ecucDataModel);

        // The following part shall be generated by Copilot based on the instructions in COPILOT_INSTRUCTIONS.md
        // Copilot: start writing your code here

        // Get all EcucPdu objects and display their names and lengths
        System.out.println("All EcucPdu names and lengths:");
        
        // Use a Set to store unique EcucPdu objects (to avoid duplicates)
        java.util.Set<ecuc.EcucPdu> uniqueEcucPdus = new java.util.HashSet<>();
        
        // Extract EcucPdu objects from Com module (ComIPdus)
        for (com.ComIPdu comIpdu : ecucDataModel.getCom().getComIPdus()) {
            uniqueEcucPdus.add(comIpdu.getEcucPduRef());
        }
        
        // Extract EcucPdu objects from PduR module (Source PDUs)
        for (pdur.PduRSrcPdu srcPdu : ecucDataModel.getPduR().getPduRSrcPdus()) {
            uniqueEcucPdus.add(srcPdu.getEcucPduRef());
        }
        
        // Extract EcucPdu objects from PduR module (Destination PDUs)
        for (pdur.PduRDestPdu destPdu : ecucDataModel.getPduR().getPduRDestPdus()) {
            uniqueEcucPdus.add(destPdu.getEcucPduRef());
        }
        
        // Extract EcucPdu objects from CanIf module (CanIfPduCfgs)
        for (can.CanIfChannel channel : ecucDataModel.getCanIf().getCanIfChannels().values()) {
            for (can.CanIfPduCfg pduCfg : channel.getCanIfPdus()) {
                uniqueEcucPdus.add(pduCfg.getEcucPduRef());
            }
        }
        
        // Display all unique EcucPdu names and lengths
        if (uniqueEcucPdus.isEmpty()) {
            System.out.println("No EcucPdus found in the model.");
        } else {
            for (ecuc.EcucPdu ecucPdu : uniqueEcucPdus) {
                System.out.println("Name: " + ecucPdu.getPduName() + ", Length: " + ecucPdu.getPduLength());
            }
            System.out.println("Total number of unique EcucPdus: " + uniqueEcucPdus.size());
        }

        // Copilot: stop writing your code here
    }
}
